version: '3.1'
services:

  odoo:
    user: root
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: sleep infinity

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo