version: "3"
services:
  odoo:
    # user: root
    image: odoobase:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: sleep infinity
    volumes:
      # Uncomment this part if want to use default odoo image from the commnunity.
      # Uncomment also postCreate command in .devcontainer.json file
      # - ./extra-addons:/usr/lib/python3/dist-packages/odoo/extra-addons:cached
      - ./config:/usr/lib/python3/dist-packages/odoo/config:cached
      - ~/.ssh:/home/odoo/.ssh:ro

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=odoo
      - PGADMIN_DEFAULT_EMAIL=odoo@odoo.home
    ports:
      - 8080:80
    depends_on:
      - db
